fix: Connection Instability with socketTimeout Parameter
valkey-io/iovalkey pull request #9
Opened 2024-10-08 11:49 UTC by pinkiesky

This PR is fixing https://github.com/redis/ioredis/issues/1919 issue (When setting the `socketTimeout` parameter to a non-zero value, the Redis connection becomes unstable after startup)

--- 

The problem is that the `auth` command is sent before DataHandler is created on connection startup. This ruins the correct listener orders--the parser listener shall execute before the other ones.

To avoid this, I replaced `on` with `prependListener` to ensure the correct order.

2024-10-12 05:21 UTC, mcollina requested changes
Thanks for opening a PR! Can you please add a unit test?

2024-10-12 08:30 UTC, alzinin commented
Sure, no problem

2024-10-23 20:10 UTC, pinkiesky commented
I just added the small unit for the changed subscribe logic, but I also noted that we missed commits that add "socketTimeout" to the lib. It happened because the socketTimeout was added after the fork was created

- https://github.com/redis/ioredis/commit/673ac77d9d88bd461110da7b4a8b2b98fb45f845
- https://github.com/redis/ioredis/commit/558497cba8dc7487c06c7765ddbe12b479bd9b9b

I can propose merging this PR (if you don't mind), and later, we will copy these missed commits to the repo. @mcollina 
is it a good way to handle this?

2024-10-23 20:55 UTC, mcollina commented
Can you open a separate PR with those two commits? We'll land that before this.

2024-10-30 14:40 UTC, mcollina approved these changes
lgtm

2024-10-30 14:41 UTC, mcollina commented
The test does not really cover the use case of the bug. Can you add a test that actually reproduce the loop?

2024-10-30 14:44 UTC, pinkiesky commented
> The test does not really cover the use case of the bug. Can you add a test that actually reproduce the loop?

The best idea I got is to create functional one for the case. Yes, I will

2024-11-05 11:29 UTC, pinkiesky commented
A functional test for socketTimeout was just added

@mcollina, could you check it and provide feedback please?

2024-11-05 11:42 UTC, mcollina approved these changes
lgtm

2024-11-05 11:42 UTC, merged